apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dpo-app
  template:
    metadata:
      labels:
        app: dpo-app
    spec:
      containers:
      - name: dpo-app
        image: pharesd/dpo-app:v5
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: dpo-app
spec:
  selector:
    app: dpo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

